const EXPLORER_THEPOWER_URL = import.meta.env.VITE_EXPLORER_THEPOWER_URL!;
const WALLET_THEPOWER_URL = import.meta.env.VITE_WALLET_THEPOWER_URL!;
const HUB_THEPOWER_URL = import.meta.env.VITE_HUB_THEPOWER_URL!;
const FAUCET_THEPOWER_URL = import.meta.env.VITE_FAUCET_THEPOWER_URL!;

export default {
  EXPLORER_THEPOWER_URL,
  WALLET_THEPOWER_URL,
  HUB_THEPOWER_URL,
  FAUCET_THEPOWER_URL
};
