import { ChainId } from 'buy/types';

const DEFAULT_CHAIN_ID = +import.meta.env.VITE_DEFAULT_CHAIN_ID as ChainId;

const C97_C3_BRIDGE_EVM_CONTRACT_ADDRESS = import.meta.env
  .VITE_C97_C3_BRIDGE_EVM_CONTRACT_ADDRESS;
const C97_C3_BRIDGE_POWER_CONTRACT_ADDRESS = import.meta.env
  .VITE_C97_C3_BRIDGE_POWER_CONTRACT_ADDRESS;

const C97_C3_SWAP_USDC_TO_SK_EVM_CONTRACT_ADDRESS = import.meta.env
  .VITE_C97_C3_SWAP_USDC_TO_SK_EVM_CONTRACT_ADDRESS;
const C97_C3_SWAP_USDT_TO_SK_EVM_CONTRACT_ADDRESS = import.meta.env
  .VITE_C97_C3_SWAP_USDT_TO_SK_EVM_CONTRACT_ADDRESS;

const C97_WSK_EVM_CONTRACT_ADDRESS = import.meta.env
  .VITE_C97_WSK_EVM_CONTRACT_ADDRESS;
const C97_USDC_EVM_CONTRACT_ADDRESS = import.meta.env
  .VITE_C97_USDC_EVM_CONTRACT_ADDRESS;
const C97_USDT_EVM_CONTRACT_ADDRESS = import.meta.env
  .VITE_C97_USDT_EVM_CONTRACT_ADDRESS;

const C56_C100501_BRIDGE_EVM_CONTRACT_ADDRESS = import.meta.env
  .VITE_C56_C100501_BRIDGE_EVM_CONTRACT_ADDRESS;
const C56_C100501_BRIDGE_POWER_CONTRACT_ADDRESS = import.meta.env
  .VITE_C56_C100501_BRIDGE_POWER_CONTRACT_ADDRESS;

const C56_C100501_SWAP_USDC_TO_SK_EVM_CONTRACT_ADDRESS = import.meta.env
  .VITE_C56_C100501_SWAP_USDC_TO_SK_EVM_CONTRACT_ADDRESS;
const C56_C100501_SWAP_USDT_TO_SK_EVM_CONTRACT_ADDRESS = import.meta.env
  .VITE_C56_C100501_SWAP_USDT_TO_SK_EVM_CONTRACT_ADDRESS;

const C56_C100501_WSK_EVM_CONTRACT_ADDRESS = import.meta.env
  .VITE_C56_C100501_WSK_EVM_CONTRACT_ADDRESS;
const C56_C100501_USDC_EVM_CONTRACT_ADDRESS = import.meta.env
  .VITE_C56_C100501_USDC_EVM_CONTRACT_ADDRESS;
const C56_C100501_USDT_EVM_CONTRACT_ADDRESS = import.meta.env
  .VITE_C56_C100501_USDT_EVM_CONTRACT_ADDRESS;

const ITEZ_API_URL = import.meta.env.VITE_ITEZ_API_URL!;
const ITEZ_PARTNER_TOKEN = import.meta.env.VITE_ITEZ_PARTNER_TOKEN!;

const PUBLIC_PROJECT_ID = import.meta.env.VITE_PUBLIC_PROJECT_ID!;

const EXPLORER_THEPOWER_URL = import.meta.env.VITE_EXPLORER_THEPOWER_URL!;
const BUY_THEPOWER_URL = import.meta.env.VITE_BUY_THEPOWER_URL!;
const WALLET_THEPOWER_URL = import.meta.env.VITE_WALLET_THEPOWER_URL!;
const HUB_THEPOWER_URL = import.meta.env.VITE_HUB_THEPOWER_URL!;
const FAUCET_THEPOWER_URL = import.meta.env.VITE_FAUCET_THEPOWER_URL!;

const VESTING_CONTRACT_ADDRESS = import.meta.env.VITE_VESTING_CONTRACT_ADDRESS;

export default {
  DEFAULT_CHAIN_ID,

  C97_C3_BRIDGE_EVM_CONTRACT_ADDRESS,
  C97_C3_BRIDGE_POWER_CONTRACT_ADDRESS,

  C97_C3_SWAP_USDC_TO_SK_EVM_CONTRACT_ADDRESS,
  C97_C3_SWAP_USDT_TO_SK_EVM_CONTRACT_ADDRESS,

  C97_WSK_EVM_CONTRACT_ADDRESS,
  C97_USDC_EVM_CONTRACT_ADDRESS,
  C97_USDT_EVM_CONTRACT_ADDRESS,

  C56_C100501_BRIDGE_EVM_CONTRACT_ADDRESS,
  C56_C100501_BRIDGE_POWER_CONTRACT_ADDRESS,

  C56_C100501_SWAP_USDC_TO_SK_EVM_CONTRACT_ADDRESS,
  C56_C100501_SWAP_USDT_TO_SK_EVM_CONTRACT_ADDRESS,

  C56_C100501_WSK_EVM_CONTRACT_ADDRESS,
  C56_C100501_USDC_EVM_CONTRACT_ADDRESS,
  C56_C100501_USDT_EVM_CONTRACT_ADDRESS,

  ITEZ_API_URL,
  ITEZ_PARTNER_TOKEN,

  PUBLIC_PROJECT_ID,

  EXPLORER_THEPOWER_URL,
  BUY_THEPOWER_URL,
  WALLET_THEPOWER_URL,
  HUB_THEPOWER_URL,
  FAUCET_THEPOWER_URL,

  VESTING_CONTRACT_ADDRESS
};
