const DEFAULT_CHAIN_ID = +(import.meta.env.VITE_DEFAULT_CHAIN_ID as string);

const EXPLORER_THEPOWER_URL = import.meta.env.VITE_EXPLORER_THEPOWER_URL!;
const BUY_THEPOWER_URL = import.meta.env.VITE_BUY_THEPOWER_URL!;
const WALLET_THEPOWER_URL = import.meta.env.VITE_WALLET_THEPOWER_URL!;
const HUB_THEPOWER_URL = import.meta.env.VITE_HUB_THEPOWER_URL!;
const FAUCET_THEPOWER_URL = import.meta.env.VITE_FAUCET_THEPOWER_URL!;

export default {
  DEFAULT_CHAIN_ID,

  EXPLORER_THEPOWER_URL,
  BUY_THEPOWER_URL,
  WALLET_THEPOWER_URL,
  HUB_THEPOWER_URL,
  FAUCET_THEPOWER_URL
};
